/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VendorsAddRouteImport } from './routes/vendors/add'
import { Route as AdminVendorsIndexRouteImport } from './routes/admin/vendors/index'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminVendorsAddRouteImport } from './routes/admin/vendors/add'
import { Route as AdminRfpCreateRouteImport } from './routes/admin/rfp/create'
import { Route as VendorsRfpIdIndexRouteImport } from './routes/vendors/rfp/$id/index'
import { Route as AdminRfpIdIndexRouteImport } from './routes/admin/rfp/$id/index'
import { Route as AdminRfpIdEditIndexRouteImport } from './routes/admin/rfp/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsAddRoute = VendorsAddRouteImport.update({
  id: '/vendors/add',
  path: '/vendors/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsIndexRoute = AdminVendorsIndexRouteImport.update({
  id: '/admin/vendors/',
  path: '/admin/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsAddRoute = AdminVendorsAddRouteImport.update({
  id: '/admin/vendors/add',
  path: '/admin/vendors/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfpCreateRoute = AdminRfpCreateRouteImport.update({
  id: '/admin/rfp/create',
  path: '/admin/rfp/create',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRfpIdIndexRoute = VendorsRfpIdIndexRouteImport.update({
  id: '/vendors/rfp/$id/',
  path: '/vendors/rfp/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfpIdIndexRoute = AdminRfpIdIndexRouteImport.update({
  id: '/admin/rfp/$id/',
  path: '/admin/rfp/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRfpIdEditIndexRoute = AdminRfpIdEditIndexRouteImport.update({
  id: '/admin/rfp/$id/edit/',
  path: '/admin/rfp/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vendors/add': typeof VendorsAddRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/admin/rfp/create': typeof AdminRfpCreateRoute
  '/admin/vendors/add': typeof AdminVendorsAddRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/rfp/$id/': typeof AdminRfpIdIndexRoute
  '/vendors/rfp/$id/': typeof VendorsRfpIdIndexRoute
  '/admin/rfp/$id/edit/': typeof AdminRfpIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vendors/add': typeof VendorsAddRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/admin/rfp/create': typeof AdminRfpCreateRoute
  '/admin/vendors/add': typeof AdminVendorsAddRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/vendors': typeof AdminVendorsIndexRoute
  '/admin/rfp/$id': typeof AdminRfpIdIndexRoute
  '/vendors/rfp/$id': typeof VendorsRfpIdIndexRoute
  '/admin/rfp/$id/edit': typeof AdminRfpIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vendors/add': typeof VendorsAddRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/admin/rfp/create': typeof AdminRfpCreateRoute
  '/admin/vendors/add': typeof AdminVendorsAddRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/vendors/': typeof AdminVendorsIndexRoute
  '/admin/rfp/$id/': typeof AdminRfpIdIndexRoute
  '/vendors/rfp/$id/': typeof VendorsRfpIdIndexRoute
  '/admin/rfp/$id/edit/': typeof AdminRfpIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/vendors/add'
    | '/admin/'
    | '/login/'
    | '/vendors/'
    | '/admin/rfp/create'
    | '/admin/vendors/add'
    | '/admin/categories/'
    | '/admin/vendors/'
    | '/admin/rfp/$id/'
    | '/vendors/rfp/$id/'
    | '/admin/rfp/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/vendors/add'
    | '/admin'
    | '/login'
    | '/vendors'
    | '/admin/rfp/create'
    | '/admin/vendors/add'
    | '/admin/categories'
    | '/admin/vendors'
    | '/admin/rfp/$id'
    | '/vendors/rfp/$id'
    | '/admin/rfp/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/vendors/add'
    | '/admin/'
    | '/login/'
    | '/vendors/'
    | '/admin/rfp/create'
    | '/admin/vendors/add'
    | '/admin/categories/'
    | '/admin/vendors/'
    | '/admin/rfp/$id/'
    | '/vendors/rfp/$id/'
    | '/admin/rfp/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VendorsAddRoute: typeof VendorsAddRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  AdminRfpCreateRoute: typeof AdminRfpCreateRoute
  AdminVendorsAddRoute: typeof AdminVendorsAddRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminVendorsIndexRoute: typeof AdminVendorsIndexRoute
  AdminRfpIdIndexRoute: typeof AdminRfpIdIndexRoute
  VendorsRfpIdIndexRoute: typeof VendorsRfpIdIndexRoute
  AdminRfpIdEditIndexRoute: typeof AdminRfpIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/add': {
      id: '/vendors/add'
      path: '/vendors/add'
      fullPath: '/vendors/add'
      preLoaderRoute: typeof VendorsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/': {
      id: '/admin/vendors/'
      path: '/admin/vendors'
      fullPath: '/admin/vendors/'
      preLoaderRoute: typeof AdminVendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors/add': {
      id: '/admin/vendors/add'
      path: '/admin/vendors/add'
      fullPath: '/admin/vendors/add'
      preLoaderRoute: typeof AdminVendorsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfp/create': {
      id: '/admin/rfp/create'
      path: '/admin/rfp/create'
      fullPath: '/admin/rfp/create'
      preLoaderRoute: typeof AdminRfpCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/rfp/$id/': {
      id: '/vendors/rfp/$id/'
      path: '/vendors/rfp/$id'
      fullPath: '/vendors/rfp/$id/'
      preLoaderRoute: typeof VendorsRfpIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfp/$id/': {
      id: '/admin/rfp/$id/'
      path: '/admin/rfp/$id'
      fullPath: '/admin/rfp/$id/'
      preLoaderRoute: typeof AdminRfpIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rfp/$id/edit/': {
      id: '/admin/rfp/$id/edit/'
      path: '/admin/rfp/$id/edit'
      fullPath: '/admin/rfp/$id/edit/'
      preLoaderRoute: typeof AdminRfpIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VendorsAddRoute: VendorsAddRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  AdminRfpCreateRoute: AdminRfpCreateRoute,
  AdminVendorsAddRoute: AdminVendorsAddRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminVendorsIndexRoute: AdminVendorsIndexRoute,
  AdminRfpIdIndexRoute: AdminRfpIdIndexRoute,
  VendorsRfpIdIndexRoute: VendorsRfpIdIndexRoute,
  AdminRfpIdEditIndexRoute: AdminRfpIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
